### ISSUE TITLE
Animation loops

### ISSUE THREAD

**Issue by philhogg** [Rythian2277/Luanoid#9]
I've noticed that when using MoveToFinished the state of the luanoid briefly reverts to an idle state. For paths that have lots of close nodes, this creates a stutter in the animation because the idle state causes the walk animation to restart.

Is there a way to build in a debounce so that smaller pauses are ignored so that animations can continue?

**Comment by raphtalia** [comment]
This repository is no longer being maintained and has been moved [here](https://github.com/raphtalia/Luanoid). Feel free to recreate this issue on the new repository if this issue still exists.
